/**
 * Data layer — MySQL via Sequelize.
 *
 * Why Sequelize rather than raw SQL: the report payload is a deep, evolving
 * JSON blob. Sequelize's JSON column stores it natively in MySQL 5.7+ while the
 * relational columns (agent, status, domain) stay properly indexed for the
 * list / filter / cache queries the app actually runs.
 *
 * DIALECT: defaults to MySQL. Set DB_DIALECT=sqlite for the local test harness —
 * identical schema, zero setup. No application code branches on dialect.
 */

const { Sequelize, DataTypes, Op } = require('sequelize');
const crypto = require('crypto');

// ---------------------------------------------------------------------------
// Field-level encryption for API keys. Keys cost real money per call, so they
// are never stored in plaintext and never leave the server unmasked.
// ---------------------------------------------------------------------------
const ALGO = 'aes-256-gcm';
const secret = () => {
  const k = process.env.ENCRYPTION_KEY || '';
  if (k.length < 32) throw new Error('ENCRYPTION_KEY must be at least 32 characters');
  return crypto.createHash('sha256').update(k).digest();
};

function encrypt(text) {
  if (!text) return '';
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGO, secret(), iv);
  const enc = Buffer.concat([cipher.update(String(text), 'utf8'), cipher.final()]);
  return [iv.toString('hex'), cipher.getAuthTag().toString('hex'), enc.toString('hex')].join(':');
}

function decrypt(payload) {
  if (!payload || !String(payload).includes(':')) return '';
  try {
    const [iv, tag, data] = String(payload).split(':');
    const d = crypto.createDecipheriv(ALGO, secret(), Buffer.from(iv, 'hex'));
    d.setAuthTag(Buffer.from(tag, 'hex'));
    return Buffer.concat([d.update(Buffer.from(data, 'hex')), d.final()]).toString('utf8');
  } catch {
    return ''; // fail closed on tampered ciphertext
  }
}

// ---------------------------------------------------------------------------
// Connection
// ---------------------------------------------------------------------------
const dialect = process.env.DB_DIALECT || 'mysql';

const sequelize =
  dialect === 'sqlite'
    ? new Sequelize({
        dialect: 'sqlite',
        storage: process.env.DB_STORAGE || './storage/qtonix.sqlite',
        logging: false,
      })
    : new Sequelize(
        process.env.DB_NAME || 'qtonix_audit',
        process.env.DB_USER || 'root',
        process.env.DB_PASS || '',
        {
          host: process.env.DB_HOST || '127.0.0.1',
          port: Number(process.env.DB_PORT || 3306),
          dialect: 'mysql',
          logging: false,
          define: { charset: 'utf8mb4', collate: 'utf8mb4_unicode_ci' },
          pool: { max: 10, min: 0, idle: 10000 },
        }
      );

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

const User = sequelize.define(
  'User',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    name: { type: DataTypes.STRING(120), allowNull: false },
    email: { type: DataTypes.STRING(180), allowNull: false, unique: true },
    passwordHash: { type: DataTypes.STRING(255), allowNull: false },
    phone: { type: DataTypes.STRING(40), defaultValue: '' },
    designation: { type: DataTypes.STRING(80), defaultValue: 'Sales Executive' },
    // Team location and shift, for roster/ownership context.
    team: { type: DataTypes.ENUM('Bhubaneswar', 'Kolkata'), defaultValue: 'Bhubaneswar' },
    shift: { type: DataTypes.ENUM('Morning', 'Night'), defaultValue: 'Morning' },
    // Pseudonyms an agent uses with clients (comma-separated list stored as JSON).
    aliases: { type: DataTypes.JSON, defaultValue: [] },
    // 'leadmanager' adds leads generated by the pre-sales team and assigns
    // them to sellers. They never own a lead or carry a sales target, so they
    // sit outside the org chart, leaderboards and reviews entirely.
    role: { type: DataTypes.ENUM('agent', 'manager', 'admin', 'leadmanager'), defaultValue: 'agent' },
    // Finer job classification within the 'agent' role. 'bde' = Business
    // Development Executive (cold calls + inbound, monthly sales target);
    // 'presales' = Pre-Sales Executive (cold calls only, daily transfer target
    // + monthly sales target). Managers/admins leave this null.
    jobType: { type: DataTypes.ENUM('bde', 'presales'), allowNull: true },
    // Reporting line: BDE/Pre-Sales report to a manager (managerId set);
    // managers report directly to admin (managerId null).
    managerId: { type: DataTypes.INTEGER, allowNull: true },
    // Targets (all monetary values in USD). Shape:
    // { transfer: { enabled, daily, monthly }, sales: { enabled, monthly },
    //   team: { enabled, monthly } }  — team only meaningful for managers.
    targets: {
      type: DataTypes.JSON,
      defaultValue: { transfer: { enabled: false, daily: 0, monthly: 0 }, sales: { enabled: false, monthly: 0 }, team: { enabled: false, monthly: 0 }, leadGen: { enabled: false, monthly: 0 } },
    },
    // For managers: which team+shift groups they oversee, e.g.
    // [{ team:'Bhubaneswar', shift:'Morning' }, { team:'Kolkata', shift:'Night' }].
    // A manager sees every lead owned by an agent whose team+shift matches any
    // entry here, plus their own leads. Admin assigns these explicitly.
    managerScopes: { type: DataTypes.JSON, defaultValue: [] },
    active: { type: DataTypes.BOOLEAN, defaultValue: true },
    // Archived = a departed agent kept only for historical records (past
    // monthly targets/achieved). Archived users are excluded from every live
    // surface — login, dashboards, leaderboards, assignment, reviews — but stay
    // selectable in Admin → Monthly Targets so their history can be recorded.
    archived: { type: DataTypes.BOOLEAN, defaultValue: false },
    reportsRun: { type: DataTypes.INTEGER, defaultValue: 0 },
    lastLogin: { type: DataTypes.DATE },
    // Small profile photo as a data URL (base64). Kept in the DB so it survives
    // Railway's ephemeral filesystem. Shown on the leaderboard.
    avatar: { type: DataTypes.TEXT, allowNull: true },
    birthday: { type: DataTypes.DATEONLY, allowNull: true },
    workAnniversary: { type: DataTypes.DATEONLY, allowNull: true },
    // Gmail (per-user OAuth). Refresh token is encrypted at rest via the
    // model hook below. connectedEmail is the Workspace address they linked.
    gmailRefreshToken: { type: DataTypes.TEXT, allowNull: true },
    gmailConnectedEmail: { type: DataTypes.STRING, allowNull: true },
    gmailConnectedAt: { type: DataTypes.DATE, allowNull: true },
    gmailHistoryId: { type: DataTypes.STRING, allowNull: true }, // last synced marker
  },
  { tableName: 'users', indexes: [{ name: 'idx_users_role', fields: ['role'] }] }
);

const Report = sequelize.define(
  'Report',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    agentId: { type: DataTypes.INTEGER, allowNull: false },
    // Denormalised: agents get deactivated, but their reports must keep working.
    agentName: DataTypes.STRING(120),
    agentPhone: DataTypes.STRING(40),
    agentEmail: DataTypes.STRING(180),
    agentDesignation: DataTypes.STRING(80),

    website: { type: DataTypes.STRING(255), allowNull: false },
    domain: { type: DataTypes.STRING(190) },
    businessName: { type: DataTypes.STRING(190), allowNull: false },
    customerName: { type: DataTypes.STRING(190), allowNull: false },
    services: { type: DataTypes.JSON, defaultValue: [] },
    country: { type: DataTypes.STRING(4), defaultValue: 'us' },
    location: DataTypes.STRING(190),

    status: { type: DataTypes.ENUM('queued', 'running', 'complete', 'failed'), defaultValue: 'queued' },
    progress: { type: DataTypes.INTEGER, defaultValue: 0 },
    currentStep: DataTypes.STRING(120),
    error: DataTypes.TEXT,

    scores: { type: DataTypes.JSON, defaultValue: {} },
    headline: { type: DataTypes.JSON, defaultValue: {} },
    summary: { type: DataTypes.JSON, defaultValue: {} },
    // Full render payload. MySQL JSON handles it natively; it is large
    // (~100-300KB) so it is never selected in list queries.
    data: { type: DataTypes.JSON, defaultValue: {} },
    opportunityValue: { type: DataTypes.JSON, defaultValue: {} },
    // Set when the report is being "refreshed": the job reuses the previously
    // fetched SE Ranking data (stored in `data`) and only re-runs the crawl and
    // the Claude AI analysis, so a refresh doesn't spend SE Ranking credits.
    refreshMode: { type: DataTypes.BOOLEAN, defaultValue: false },

    // ---- CRM: how the sales team tracks the prospect after the report ----
    stage: {
      type: DataTypes.ENUM(
        'new', 'hot', 'cold', 'ni', 'contacted', 'interested',
        'proposal', 'negotiation', 'won', 'lost'
      ),
      defaultValue: 'new',
    },
    tags: { type: DataTypes.JSON, defaultValue: [] },   // what they asked for
    remark: { type: DataTypes.TEXT },                    // legacy single note (kept for back-compat)
    // Timestamped remark history: [{ text, time, author }]. Never overwritten —
    // each new note is appended, so the full call history is always visible.
    remarks: { type: DataTypes.JSON, defaultValue: [] },
    // Unified activity timeline: [{ type:'remark'|'stage'|'request', text, time, author }]
    // — every remark, stage change and request change, newest last.
    activity: { type: DataTypes.JSON, defaultValue: [] },
    followUpAt: { type: DataTypes.DATE },

    // ---- Customer contact details (CRM), captured before running a report ----
    customerPhone: { type: DataTypes.STRING(40), defaultValue: '' },
    customerEmail: { type: DataTypes.STRING(180), defaultValue: '' },
    customerCountry: { type: DataTypes.STRING(60), defaultValue: '' },
    customerCompany: { type: DataTypes.STRING(190), defaultValue: '' },

    isDemo: { type: DataTypes.BOOLEAN, defaultValue: false },
    pdfPath: DataTypes.STRING(255),
    htmlPath: DataTypes.STRING(255),
    creditsUsed: DataTypes.INTEGER,
    durationMs: DataTypes.INTEGER,
    completedAt: DataTypes.DATE,
  },
  {
    tableName: 'reports',
    // Every index is explicitly named. Without a name, Sequelize's alter-sync
    // cannot tell an existing index from a new one and appends a numbered
    // duplicate on each boot, eventually breaching MySQL's 64-key ceiling.
    indexes: [
      { name: 'idx_reports_agent', fields: ['agentId'] },
      { name: 'idx_reports_status', fields: ['status'] },
      { name: 'idx_reports_domain', fields: ['domain'] }, // powers the 7-day cache lookup
      { name: 'idx_reports_is_demo', fields: ['isDemo'] },
      { name: 'idx_reports_stage', fields: ['stage'] },   // pipeline filtering
    ],
  }
);

// ---------------------------------------------------------------------------
// Lead — the central CRM entity. A lead is a prospect owned by an agent/manager,
// worked through a pipeline, with notes, activities (tasks/calls), deals and
// linked reports hung off it. Dropdown *values* (sources, services, tags, deal
// stages) are configured in Settings so admin can edit them without a deploy.
// ---------------------------------------------------------------------------
const Lead = sequelize.define(
  'Lead',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    // Ownership: who the lead belongs to (drives visibility). Denormalised
    // owner team/shift so manager visibility queries stay simple and survive
    // the owner later changing team.
    ownerId: { type: DataTypes.INTEGER, allowNull: false },
    ownerName: { type: DataTypes.STRING(120) },
    ownerTeam: { type: DataTypes.ENUM('Bhubaneswar', 'Kolkata'), defaultValue: 'Bhubaneswar' },
    ownerShift: { type: DataTypes.ENUM('Morning', 'Night'), defaultValue: 'Morning' },

    // Contact information
    firstName: { type: DataTypes.STRING(120), allowNull: false },
    lastName: { type: DataTypes.STRING(120), defaultValue: '' },
    website: { type: DataTypes.STRING(255), defaultValue: '' },
    domain: { type: DataTypes.STRING(190), defaultValue: '' }, // normalised, for report matching
    email: { type: DataTypes.STRING(180), defaultValue: '' },
    secondaryEmail: { type: DataTypes.STRING(180), defaultValue: '' },
    mobile: { type: DataTypes.STRING(40), defaultValue: '' },
    phone: { type: DataTypes.STRING(40), defaultValue: '' },

    // Classification (values validated against Settings-configured lists)
    leadSource: { type: DataTypes.STRING(60), defaultValue: '' },
    generatedBy: { type: DataTypes.STRING(120), defaultValue: '' },
    // Which pre-sales inbox a Pre-Sales lead arrived from. Visible only to lead
    // managers and admins.
    generatedFromEmail: { type: DataTypes.STRING(180), defaultValue: '' },
    status: { type: DataTypes.STRING(40), defaultValue: 'new' },
    servicesInterested: { type: DataTypes.JSON, defaultValue: [] },
    tags: { type: DataTypes.JSON, defaultValue: [] },

    // Geography
    country: { type: DataTypes.STRING(80), defaultValue: '' },
    city: { type: DataTypes.STRING(120), defaultValue: '' },
    timezone: { type: DataTypes.STRING(80), defaultValue: '' },

    additionalInfo: { type: DataTypes.TEXT, defaultValue: '' },

    // Sub-collections stored as JSON for now (simple, migration-friendly).
    // Each: notes[{id,text,time,author}], activities[{id,kind:'task'|'call',...}],
    // deals[{id,name,stage,currency,amount,expectedClose,service,remark,...}],
    // timeline[{type,text,time,author}] (auto-built from every change).
    notes: { type: DataTypes.JSON, defaultValue: [] },
    activities: { type: DataTypes.JSON, defaultValue: [] },
    deals: { type: DataTypes.JSON, defaultValue: [] },
    // Cached AI business brief for this lead's website (see
    // services/businessBrief.js). Regenerated on demand; the UI offers a
    // refresh once it is more than a week old.
    aiBrief: { type: DataTypes.JSON, defaultValue: null },
    timeline: { type: DataTypes.JSON, defaultValue: [] },

    lastActivityAt: { type: DataTypes.DATE },
    convertedAt: { type: DataTypes.DATE },
    // Set whenever ownership changes to a (new) user — powers "assigned today".
    assignedAt: { type: DataTypes.DATE },
    /**
     * Who keyed this lead in. Distinct from ownerId: a lead manager enters a
     * pre-sales lead and hands it to a seller, so the seller owns it while the
     * lead manager keeps visibility of everything they entered (which is what
     * their dashboard and CSV export are scoped to).
     */
    enteredById: { type: DataTypes.INTEGER, allowNull: true },
    // Marks a lead whose generated date differs from its created (entry) date —
    // i.e. a historical import. Used to scope the 24-hour first-reply rule,
    // which only applies when the two dates are the same.
    backDated: { type: DataTypes.BOOLEAN, defaultValue: false },
    // When the lead was actually generated in the real world. For a normal add
    // this equals createdAt; for a back-dated import it's the chosen historical
    // date. Shown in the UI as "Lead generated"; createdAt (entry moment) is the
    // anchor for the untouched clock and stays hidden.
    generatedAt: { type: DataTypes.DATE, allowNull: true },
    // The agent who generated a call-back prospect. Ownership can later move to
    // whoever it's transferred to, but the originator keeps visibility of the
    // lead they created — so this is recorded separately from ownerId.
    generatedById: { type: DataTypes.INTEGER, allowNull: true },
    // The agreed call-back time for a call-back-stage lead. Drives the
    // countdown shown in the Call Backs list.
    callbackAt: { type: DataTypes.DATE, allowNull: true },
    // When a prospect was transferred and by whom, for the audit trail and the
    // dashboard's "call transfers today" count.
    transferredAt: { type: DataTypes.DATE },
    transferredById: { type: DataTypes.INTEGER, allowNull: true },
    transferredByName: { type: DataTypes.STRING(120), defaultValue: '' },
    transferredToId: { type: DataTypes.INTEGER, allowNull: true },
    enteredByName: { type: DataTypes.STRING(120), defaultValue: '' },
    /**
     * First-reply workflow for pre-sales leads. The owner either answers the
     * enquiry themselves or hands a draft to the lead manager to send on their
     * behalf — but either way it must happen within 24 hours of assignment.
     *
     *   firstReplyMode : '' | 'self' | 'leadmanager'
     *   firstDraft     : the text handed over, when mode is 'leadmanager'
     *   firstReplyDoneAt : set when the draft is submitted or the owner marks
     *                      their own reply sent. Null means the clock is still
     *                      running, which is what turns the timeline row red.
     */
    firstReplyMode: { type: DataTypes.STRING(20), defaultValue: '' },
    firstDraftSubject: { type: DataTypes.STRING(300), defaultValue: '' },
    firstDraft: { type: DataTypes.TEXT },
    firstDraftAt: { type: DataTypes.DATE },
    // Whether the lead manager has read the submitted draft and sent the real
    // email. A draft can be submitted (clock stopped) but not yet read.
    firstDraftRead: { type: DataTypes.BOOLEAN, defaultValue: false },
    firstDraftReadAt: { type: DataTypes.DATE },
    firstReplyDoneAt: { type: DataTypes.DATE },
    /**
     * Reminder draft: the agent writes a follow-up email (subject + body) and
     * submits it to the lead manager, who sends it and marks it received. Same
     * shape as the first-reply draft but a separate stage.
     */
    reminderSubject: { type: DataTypes.STRING(300), defaultValue: '' },
    reminderDraft: { type: DataTypes.TEXT },
    reminderDraftAt: { type: DataTypes.DATE },
    reminderReceived: { type: DataTypes.BOOLEAN, defaultValue: false },
    reminderReceivedAt: { type: DataTypes.DATE },
    /**
     * A lead manager can ask the owner to chase a lead. Cleared once the owner
     * responds, so it works as a simple one-shot nudge.
     */
    reminderRequestedAt: { type: DataTypes.DATE },
    reminderRequestedBy: { type: DataTypes.STRING(120), defaultValue: '' },
    reminderNote: { type: DataTypes.STRING(500), defaultValue: '' },
    // If this lead originated from a migrated report, keep the link.
    sourceReportId: { type: DataTypes.INTEGER },
  },
  {
    tableName: 'leads',
    indexes: [
      { name: 'idx_leads_owner', fields: ['ownerId'] },
      { name: 'idx_leads_team_shift', fields: ['ownerTeam', 'ownerShift'] }, // manager visibility
      { name: 'idx_leads_domain', fields: ['domain'] },                      // report auto-linking
      { name: 'idx_leads_status', fields: ['status'] },
    ],
  }
);

// Add _id alias mirroring id (frontend convenience, matches Report/User pattern).
Lead.prototype.toJSON = function () {
  const v = { ...this.get() };
  v._id = v.id;
  return v;
};

// Link reports to leads via a plain nullable column (no hard FK constraint —
// keeps SQLite alter-table migrations simple and avoids constraint failures
// when adding the column to a table that already has rows).
Report.rawAttributes.leadId = { type: DataTypes.INTEGER, allowNull: true };
Report.refreshAttributes();

const Settings = sequelize.define(
  'Settings',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    singleton: { type: DataTypes.STRING(20), defaultValue: 'settings', unique: true },

    companyName: { type: DataTypes.STRING(190), defaultValue: 'Qtonix Software Pvt. Ltd.' },
    companyShort: { type: DataTypes.STRING(60), defaultValue: 'Qtonix' },
    logoPath: { type: DataTypes.STRING(255), defaultValue: '' },
    faviconPath: { type: DataTypes.STRING(255), defaultValue: '' },
    website: { type: DataTypes.STRING(190), defaultValue: 'https://www.qtonix.com' },
    email: { type: DataTypes.STRING(190), defaultValue: 'info@qtonix.com' },
    phone: { type: DataTypes.STRING(40), defaultValue: '+91-8249016547' },
    address: { type: DataTypes.STRING(255), defaultValue: '608, 6th Floor, Utkal Signature Building, Bhubaneswar, India 752101' },

    colors: {
      type: DataTypes.JSON,
      defaultValue: { navy: '#050A1F', orange: '#FF6A00', orangeDeep: '#FF4500', blue: '#2563EB' },
    },
    fontFamily: { type: DataTypes.STRING(80), defaultValue: 'Plus Jakarta Sans' },

    apiKeys: {
      type: DataTypes.JSON,
      defaultValue: { seranking: '', anthropic: '', pagespeed: '', googlePlaces: '', imagekitPublic: '', imagekitPrivate: '', imagekitEndpoint: '', gmailClientId: '', gmailClientSecret: '' },
    },

    pricing: { type: DataTypes.JSON },
    // CRM dropdown configuration — admin-editable so new sources/services/stages
    // can be added without a code change. Defaults seed the lists you specified.
    crmConfig: {
      type: DataTypes.JSON,
      defaultValue: {
        leadSources: ['Pre-Sales', 'Cold Calling', 'Ads & Marketing', 'Referral', 'Partner', 'Inbound'],
        generatedByExtra: ['Presales'], // plus the live agent/manager list, merged at read time
        /**
         * Pre-sales team members. These people generate leads but never log in,
         * so they are names only — maintained by admin under CRM fields and
         * offered under "Generated by" once the source is Pre-Sales. The lead
         * manager's team performance figures are attributed to these names.
         */
        presalesTeam: [],
        leadStatuses: [
          { id: 'callback', label: 'Call back generated', color: '#8B5CF6' },
          { id: 'new', label: 'New lead', color: '#64748B' },
          { id: 'hot', label: 'Hot', color: '#EA580C' },
          { id: 'cold', label: 'Cold', color: '#0891B2' },
          { id: 'ni', label: 'Not interested', color: '#94A3B8' },
          { id: 'contacted', label: 'Contacted', color: '#2563EB' },
          { id: 'interested', label: 'Interested', color: '#7C3AED' },
          { id: 'proposal', label: 'Proposal sent', color: '#0D9488' },
          { id: 'negotiation', label: 'Negotiating', color: '#CA8A04' },
          { id: 'won', label: 'Won', color: '#16A34A' },
          { id: 'converted', label: 'Converted', color: '#059669' },
          { id: 'lost', label: 'Lost', color: '#DC2626' },
        ],
        servicesInterested: [
          'One-time Issue Fixing', 'Complete Digital Marketing', 'Website Design', 'Web Development',
          'eCommerce Website Development', 'Mobile App Development', 'AI Agent Development',
          'Social Media Promotion', 'Meta Ads Campaign', 'Google Ads Campaign', 'Website Maintenance',
          'Logo Design', 'Article/Blog Writing', 'PR Outreach', 'Email Newsletter Design',
          'Email Funnel Design & Manage',
        ],
        tags: ['New Lead', 'Call Back', 'Voice Mail', 'Meeting Scheduled', 'Waiting for Response', 'Contacted', 'Proposal Sent', 'Negotiating', 'Not Interested'],
        dealStages: [
          { id: 'qualification', label: 'Qualification', color: '#64748B' },
          { id: 'needs_analysis', label: 'Needs Analysis', color: '#2563EB' },
          { id: 'proposal', label: 'Proposal', color: '#7C3AED' },
          { id: 'negotiation', label: 'Negotiation', color: '#CA8A04' },
          { id: 'closed_won', label: 'Closed Won', color: '#16A34A' },
          { id: 'closed_lost', label: 'Closed Lost', color: '#DC2626' },
        ],
        dealCurrencies: ['USD', 'INR', 'EUR', 'GBP', 'AUD'],
        taskPriorities: ['Low', 'Medium', 'High', 'Urgent'],
        // Admin-maintained FX rates: units of the currency per 1 USD. Deal
        // amounts in other currencies are divided by their rate to get USD for
        // target/leaderboard maths. USD is always 1.
        fxRates: { USD: 1, INR: 83, EUR: 0.92, GBP: 0.79, AUD: 1.52 },
      },
    },

    reportValidDays: { type: DataTypes.INTEGER, defaultValue: 14 },
    dailyReportLimit: { type: DataTypes.INTEGER, defaultValue: 20 },
    /**
     * Motivator TV settings. The board runs on an unauthenticated public URL
     * (a TV browser can't log in), so access is controlled by a long random
     * token that an admin can regenerate to revoke a leaked link.
     */
    tvToken: { type: DataTypes.STRING(64) },
    tvEnabled: { type: DataTypes.BOOLEAN, defaultValue: false },
    // Ticker messages shown along the bottom of the board.
    tvAnnouncements: { type: DataTypes.JSON, defaultValue: [] },
    /**
     * Training / demo mode. When an admin enables it we mint a long random
     * token; the app is then reachable at /demo-app/<token> preloaded with
     * fabricated data so agents can be shown the whole product without seeing
     * (or being able to touch) real client records. Regenerating the token
     * instantly kills any link that has been shared too widely.
     */
    demoAppEnabled: { type: DataTypes.BOOLEAN, defaultValue: false },
    demoAppToken: { type: DataTypes.STRING(64) },
    // When the current demo link was switched on, purely so the admin screen
    // can show "running since ..." and nudge them to turn it off again.
    demoAppStartedAt: { type: DataTypes.DATE },
    cacheDays: { type: DataTypes.INTEGER, defaultValue: 7 },
    defaultCountry: { type: DataTypes.STRING(4), defaultValue: 'us' },
  },
  { tableName: 'settings' }
);

/**
 * A 1-to-1 performance review recorded by a manager (or by the admin when the
 * agent's branch+shift has no manager). Kept as a running history so HR can see
 * whether an underperformer was actually spoken to, and what was agreed.
 */
const Review = sequelize.define(
  'Review',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    agentId: { type: DataTypes.INTEGER, allowNull: false },
    agentName: DataTypes.STRING(120),
    reviewerId: { type: DataTypes.INTEGER, allowNull: false },
    reviewerName: DataTypes.STRING(120),
    // Which month this review covers, as 'YYYY-MM'.
    period: { type: DataTypes.STRING(7), allowNull: false },
    // 'agent' (manager reviews an agent) or 'manager' (admin reviews a manager
    // on team performance). Lets both live in one table without colliding.
    kind: { type: DataTypes.STRING(12), defaultValue: 'agent' },
    // System-computed bucket at the time of review: 'top' | 'ok' | 'attention'.
    band: { type: DataTypes.STRING(20) },
    // Snapshot of the numbers the conversation was based on, so later readers
    // see what the manager saw rather than today's figures.
    snapshot: { type: DataTypes.JSON, defaultValue: {} },
    // The manager's own words.
    feedback: { type: DataTypes.TEXT },
    actionPlan: { type: DataTypes.TEXT },
    // Whether the 1-to-1 actually happened.
    metOn: { type: DataTypes.DATEONLY },
    // Escalation flag for HR.
    needsHr: { type: DataTypes.BOOLEAN, defaultValue: false },
  },
  {
    tableName: 'reviews',
    indexes: [{ name: 'idx_reviews_agent', fields: ['agentId'] }, { name: 'idx_reviews_period', fields: ['period'] }, { name: 'idx_reviews_reviewer', fields: ['reviewerId'] }],
  }
);

// Per-user, per-month sales target and achieved amount. Lets an admin key in
// historical figures for months the system has no live data for (e.g. a newly
// joined agent's past six months), so reviews aren't blank. Reviews prefer the
// live-computed number and fall back to `achievedUsd` only when there's no live
// data for that user+month.
const MonthlyTarget = sequelize.define(
  'MonthlyTarget',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    userId: { type: DataTypes.INTEGER, allowNull: false },
    userName: DataTypes.STRING(120),
    role: DataTypes.STRING(20),         // snapshot of the user's role at entry time
    // 'YYYY-MM'.
    period: { type: DataTypes.STRING(7), allowNull: false },
    // Manually entered sales target and achieved amount, in USD.
    targetUsd: { type: DataTypes.FLOAT, defaultValue: 0 },
    achievedUsd: { type: DataTypes.FLOAT, defaultValue: 0 },
    enteredById: DataTypes.INTEGER,
    enteredByName: DataTypes.STRING(120),
  },
  {
    tableName: 'monthly_targets',
    indexes: [
      { name: 'idx_mt_user_period', unique: true, fields: ['userId', 'period'] },
      { name: 'idx_mt_period', fields: ['period'] },
    ],
  }
);

/**
 * Standalone AI briefs run from the AI Brief page (not tied to a lead). Cached
 * by domain: the `brief` JSON is shared, but each person who looks a domain up
 * gets their own row so it appears in their history. `sharedFrom` points at the
 * original row a cache hit copied its content from, purely for traceability.
 */
const BusinessBrief = sequelize.define(
  'BusinessBrief',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    domain: { type: DataTypes.STRING(190) },        // normalised, for cache lookup
    website: { type: DataTypes.STRING(300) },        // full URL as entered
    customerName: { type: DataTypes.STRING(190) },
    phone: { type: DataTypes.STRING(60) },
    // Who ran (or looked up) this brief — drives the visibility rules.
    agentId: { type: DataTypes.INTEGER },
    agentName: { type: DataTypes.STRING(120) },
    agentTeam: { type: DataTypes.STRING(60) },
    agentShift: { type: DataTypes.STRING(60) },
    brief: { type: DataTypes.JSON, defaultValue: null },
    // Whether this row reused a cached brief and, if so, from which row.
    cached: { type: DataTypes.BOOLEAN, defaultValue: false },
    sharedFromId: { type: DataTypes.INTEGER, allowNull: true },
  },
  {
    tableName: 'business_briefs',
    indexes: [
      { name: 'idx_brief_domain', fields: ['domain'] },
      { name: 'idx_brief_agent', fields: ['agentId'] },
    ],
  }
);

const AuditLog = sequelize.define(
  'AuditLog',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    userId: DataTypes.INTEGER,
    userName: DataTypes.STRING(120),
    action: DataTypes.STRING(60),
    target: DataTypes.STRING(190),
    meta: { type: DataTypes.JSON, defaultValue: {} },
    ip: DataTypes.STRING(60),
  },
  { tableName: 'audit_logs', indexes: [{ name: 'idx_audit_user', fields: ['userId'] }] }
);

// Synced Gmail messages, linked to a lead + the user whose mailbox they came
// from. Populated by the background Gmail sync; read by the lead detail page.
const LeadEmail = sequelize.define(
  'LeadEmail',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    leadId: { type: DataTypes.INTEGER, allowNull: false },
    userId: { type: DataTypes.INTEGER, allowNull: false }, // whose mailbox
    gmailMessageId: { type: DataTypes.STRING(120), allowNull: false },
    threadId: { type: DataTypes.STRING(120), defaultValue: '' },
    direction: { type: DataTypes.ENUM('inbound', 'outbound'), defaultValue: 'inbound' },
    fromEmail: { type: DataTypes.STRING(255), defaultValue: '' },
    fromName: { type: DataTypes.STRING(255), defaultValue: '' },
    toEmail: { type: DataTypes.TEXT, allowNull: true },
    subject: { type: DataTypes.TEXT, allowNull: true },
    snippet: { type: DataTypes.TEXT, allowNull: true },
    bodyHtml: { type: DataTypes.TEXT('long'), allowNull: true },
    bodyText: { type: DataTypes.TEXT('long'), allowNull: true },
    sentAt: { type: DataTypes.DATE },
    isRead: { type: DataTypes.BOOLEAN, defaultValue: false },
  },
  {
    tableName: 'lead_emails',
    indexes: [
      { name: 'idx_leademail_lead', fields: ['leadId'] },
      { name: 'idx_leademail_msg', unique: true, fields: ['userId', 'gmailMessageId'] },
    ],
  }
);
LeadEmail.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

User.hasMany(Report, { foreignKey: 'agentId', as: 'reports' });
Report.belongsTo(User, { foreignKey: 'agentId', as: 'agent' });

// Standalone briefs expose _id like everything else the frontend consumes.
BusinessBrief.prototype.toJSON = function () {
  const o = Object.assign({}, this.get());
  o._id = o.id;
  return o;
};

// The frontend was written against a Mongo-style `_id`. MySQL uses `id`. Rather
// than rewrite every reference, expose both: every Report serialised to JSON
// includes an `_id` mirror of `id`, so links like /reports/:id work correctly.
Report.prototype.toJSON = function () {
  const o = Object.assign({}, this.get());
  o._id = o.id;
  return o;
};

// Same _id mirror for User, and never leak the password hash to the client.
User.prototype.toJSON = function () {
  const o = Object.assign({}, this.get());
  o._id = o.id;
  delete o.passwordHash;
  o.gmailConnected = !!o.gmailRefreshToken;
  delete o.gmailRefreshToken;
  return o;
};

User.prototype.getGmailRefreshToken = function () {
  const v = this.gmailRefreshToken;
  if (!v) return '';
  return /^[0-9a-f]+:[0-9a-f]+:[0-9a-f]+$/i.test(v) ? decrypt(v) : v;
};

function encryptGmailToken(instance) {
  const v = instance.gmailRefreshToken;
  if (v && !/^[0-9a-f]+:[0-9a-f]+:[0-9a-f]+$/i.test(String(v))) {
    instance.gmailRefreshToken = encrypt(String(v));
  }
}
User.beforeCreate(encryptGmailToken);
User.beforeUpdate(encryptGmailToken);

// ---------------------------------------------------------------------------
// Encryption hooks — transparent at the model layer.
// ---------------------------------------------------------------------------
function encryptKeys(instance) {
  const keys = instance.apiKeys || {};
  const out = {};
  for (const [k, v] of Object.entries(keys)) {
    // Already-encrypted values contain ':' separators — never double-encrypt.
    out[k] = v && !String(v).includes(':') ? encrypt(v) : v;
  }
  instance.apiKeys = out;
}
Settings.beforeCreate(encryptKeys);
Settings.beforeUpdate(encryptKeys);

Settings.prototype.getKey = function (name) {
  return decrypt((this.apiKeys || {})[name]);
};

/** Never send real keys to the browser — only a masked hint that one is set. */
Settings.prototype.toSafeJSON = function () {
  const o = this.toJSON();
  o.apiKeys = Object.fromEntries(
    Object.entries(o.apiKeys || {}).map(([k, v]) => {
      const plain = decrypt(v);
      return [k, plain ? '••••••••' + plain.slice(-4) : ''];
    })
  );
  return o;
};

function defaultPricing() {
  return {
    enabled: true,
    currency: 'USD',
    symbol: '$',
    intro: 'Three ways to work together — all month-to-month, no lock-in. Every package includes monthly reporting, keyword tracking and a dedicated point of contact.',
    note: 'About paid backlinks. Some high-authority backlinks carry a direct placement cost paid to the publisher — this is a direct expense you pay, separate from your package. Qtonix handles all the research, outreach, backend conversations and setup for free — no agency markup and no management charge on top. And we only ever place genuine, relevant links.',
    guaranteeTitle: 'The risk is ours, not yours.',
    guaranteeBody: "If we don't increase your targeted traffic and enquiries within 90 days, we refund every dollar you've paid — and write you a cheque for $1,000 for your time.",
    packages: [
      {
        name: 'STARTER', price: '399', period: '/mo', oldPrice: '', recommended: false, badge: '',
        blurb: 'Getting started on a budget.',
        features: ['Keyword & competitor research', '2 SEO blogs / month', 'Directory submission: 12 / month', 'Social bookmarking: 8 / month', 'Profile creation: 8 / month', 'Q&A submission: 8 / month', 'Monthly report'],
        starFeatures: [],
      },
      {
        name: 'GROWTH', price: '549', period: '/mo', oldPrice: '799', recommended: true, badge: 'RECOMMENDED',
        blurb: 'Best value — builds the pages that capture high-intent searches. Lock now = lifetime price, even when our rates rise.',
        features: ['Everything in Starter, plus:', '3–4 SEO blogs / month', '2 landing pages / month', 'Guest posts: 2 / month', 'Article / blog submission: 8 / month', 'Infographic submission: 8 / month', 'PR submission: 1 / month', 'GMB / profile optimisation: 2 / month'],
        starFeatures: ['90-day money-back guarantee'],
      },
      {
        name: 'PREMIUM', price: '1,199', period: '/mo', oldPrice: '', recommended: false, badge: '',
        blurb: 'Maximum speed — includes link cleanup.',
        features: ['Everything in Growth, plus:', '8+ SEO blogs / month', '4+ landing pages / month', 'Full on-page SEO audit & fixes', 'Backlink audit & disavow', 'Technical SEO: speed, schema, JS fixes', 'Competitor gap analysis'],
        starFeatures: ['90-day money-back guarantee'],
      },
    ],
  };
}

/**
 * Sequelize's `sync({ alter: true })` re-creates indexes on every boot without
 * checking whether an equivalent one already exists. On MySQL this silently
 * accumulates duplicates (leads_owner_id, leads_owner_id_2, _3 …) until the
 * table hits the hard limit of 64 keys and every connection fails with
 * "Too many keys specified; max 64 keys allowed".
 *
 * Before syncing we drop the redundant copies, keeping the first index for each
 * distinct column signature. PRIMARY and UNIQUE keys are never touched, since
 * dropping those would lose real constraints.
 */
async function pruneDuplicateIndexes() {
  if (sequelize.getDialect() !== 'mysql') return;

  // Read the real index layout from information_schema. This is more reliable
  // than SHOW INDEX (whose result shape varies with how Sequelize unwraps it)
  // and lets us handle every table in the schema, not a hard-coded list.
  let rows;
  try {
    rows = await sequelize.query(
      `SELECT TABLE_NAME AS tbl, INDEX_NAME AS idx, NON_UNIQUE AS nonUnique,
              SEQ_IN_INDEX AS seq, COLUMN_NAME AS col
         FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
        ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX`,
      { type: sequelize.QueryTypes.SELECT }
    );
  } catch (e) {
    console.error('[schema] could not read index metadata:', e.message);
    return;
  }
  if (!rows || rows.length === 0) return;

  // Rebuild whole indexes from their per-column rows.
  const tables = {};
  for (const r of rows) {
    const t = (tables[r.tbl] = tables[r.tbl] || {});
    const i = (t[r.idx] = t[r.idx] || { name: r.idx, unique: Number(r.nonUnique) === 0, cols: [] });
    i.cols[Number(r.seq) - 1] = r.col;
  }

  for (const [table, indexes] of Object.entries(tables)) {
    const all = Object.values(indexes);
    const seen = new Set();
    const drop = [];

    // Sort so the canonical name is considered first: Sequelize's duplicates are
    // suffixed _2, _3 …, so the shortest name for a given signature is the
    // original one worth keeping.
    const ordered = all.slice().sort((a, b) => a.name.length - b.name.length || a.name.localeCompare(b.name));

    for (const idx of ordered) {
      if (idx.name === 'PRIMARY') continue; // never drop the primary key
      const sig = idx.cols.join(',');
      // Unique indexes are deduplicated too, but keyed separately so a UNIQUE
      // index is never mistaken for a plain one covering the same column.
      // `users.email` is the usual casualty: `unique: true` makes alter-sync add
      // email_2, email_3 … on every deploy, and those copies enforce nothing the
      // first one doesn't already guarantee.
      const key = (idx.unique ? 'U:' : 'K:') + sig;
      if (seen.has(key)) drop.push(idx.name);
      else seen.add(key);
    }

    // Safety net: MySQL allows 64 keys per table. If a table is still at or
    // near the ceiling after removing exact duplicates, shed the numbered
    // Sequelize copies (name ending _<digits>) until we're comfortably under.
    const keptCount = all.length - drop.length;
    if (keptCount > 60) {
      const numbered = all
        .filter((i) => i.name !== 'PRIMARY' && /_\d+$/.test(i.name) && !drop.includes(i.name))
        .sort((a, b) => b.name.localeCompare(a.name));
      for (const idx of numbered) {
        if (all.length - drop.length <= 40) break;
        drop.push(idx.name);
      }
    }

    for (const name of drop) {
      try {
        await sequelize.query(`ALTER TABLE \`${table}\` DROP INDEX \`${name}\``);
      } catch (e) {
        console.error(`[schema] could not drop ${table}.${name}:`, e.message);
      }
    }
    if (drop.length) {
      console.log(`[schema] ${table}: dropped ${drop.length} duplicate index(es), ${all.length - drop.length} remain`);
    }
  }
}

/** Connect, create/alter tables, guarantee the settings row exists. */
async function initDb({ sync = true } = {}) {
  await sequelize.authenticate();
  // `alter: true` adds any new columns to existing tables (e.g. when the model
  // gains fields after the tables were first created). Without it, sync() only
  // creates missing tables and leaves old ones untouched, causing
  // "Unknown column" errors after a schema change.
  if (sync) {
    // Clear out index duplicates left by previous alter-syncs first, otherwise
    // MySQL rejects the sync entirely once a table reaches 64 keys.
    await pruneDuplicateIndexes();

    // SQLite enforces foreign keys during ALTER TABLE, which can fail when
    // adding columns to tables that already hold rows. MySQL (production) does
    // not have this limitation. Briefly relax FK enforcement around sync on
    // SQLite so `alter: true` can add new columns cleanly.
    const isSqlite = sequelize.getDialect() === 'sqlite';
    if (isSqlite) await sequelize.query('PRAGMA foreign_keys = OFF');
    try {
      await sequelize.sync({ alter: true });
    } catch (e) {
      console.error('[schema] alter sync failed:', e.message);
      // A second pruning pass, then retry. The first pass may have run before
      // we knew which table was over the limit.
      try {
        await pruneDuplicateIndexes();
        await sequelize.sync({ alter: true });
        console.log('[schema] recovered after index cleanup');
      } catch (e2) {
        // Still failing: bring the tables up WITHOUT touching indexes at all.
        // Existing tables keep their current schema; the app boots and serves
        // traffic, which matters more than a perfectly-migrated schema.
        console.error('[schema] retry failed, creating tables without index sync:', e2.message);
        for (const model of Object.values(sequelize.models)) {
          try {
            await model.sync({ alter: false });
          } catch (e3) {
            console.error(`[schema] ${model.tableName}: ${e3.message}`);
          }
        }
      }
    }
    if (isSqlite) await sequelize.query('PRAGMA foreign_keys = ON');
  }
  let s = await Settings.findOne({ where: { singleton: 'settings' } });
  if (!s) s = await Settings.create({ singleton: 'settings', pricing: defaultPricing() });
  if (!s.pricing) {
    s.pricing = defaultPricing();
    await s.save();
  }
  // Backfill CRM config for installs whose settings row predates it (sync adds
  // the column but never populates existing rows). Without this the Leads
  // dropdowns come back empty on upgraded databases.
  if (!s.crmConfig || !s.crmConfig.leadSources) {
    s.crmConfig = Settings.rawAttributes.crmConfig.defaultValue;
    s.changed('crmConfig', true);
    await s.save();
  } else {
    // Merge any newly-added config keys (e.g. fxRates) into existing installs
    // without disturbing the admin's customised lists.
    const defaults = Settings.rawAttributes.crmConfig.defaultValue;
    let touched = false;
    for (const k of Object.keys(defaults)) {
      if (s.crmConfig[k] === undefined) { s.crmConfig[k] = defaults[k]; touched = true; }
    }
    if (touched) { s.changed('crmConfig', true); await s.save(); }
  }
  return s;
}

// ===========================================================================
// HR MODULE MODELS
// These are entirely separate from the Site Analysis / CRM models above. The HR
// portal is admin-plus-HR-staff only and never touches CRM data. HR staff are
// their own user population (HrUser), distinct from CRM users (User).
// ===========================================================================

// HR portal staff. Their own login population, separate from CRM `User`. Type
// is the access/user class (hr, recruiter, employee); designation is their
// human-readable title (HR Manager, Sr HR Executive, etc.) that the admin sets.
const HrUser = sequelize.define('HrUser', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(120), allowNull: false },
  employeeId: { type: DataTypes.STRING(40), allowNull: true },
  email: { type: DataTypes.STRING(160), allowNull: false, unique: true },
  passwordHash: { type: DataTypes.STRING(200), allowNull: false },
  phone: { type: DataTypes.STRING(40), defaultValue: '+91 ' },
  designation: { type: DataTypes.STRING(80), defaultValue: '' },
  // Access class within HR: hr, recruiter, manager, tl, employee.
  type: { type: DataTypes.ENUM('hr', 'recruiter', 'manager', 'tl', 'senior', 'junior', 'trainee', 'intern', 'employee'), defaultValue: 'employee' },
  branch: { type: DataTypes.STRING(80), defaultValue: 'Bhubaneswar' },
  department: { type: DataTypes.STRING(80), defaultValue: '' },
  joiningDate: { type: DataTypes.DATEONLY, allowNull: true },
  branchIncharge: { type: DataTypes.BOOLEAN, defaultValue: false },
  reportsToId: { type: DataTypes.INTEGER, allowNull: true },
  reportsToAdminId: { type: DataTypes.INTEGER, allowNull: true },
  targets: { type: DataTypes.JSON, defaultValue: { dailyInterviews: 0, monthlyOnboarding: 0 } },
  avatar: { type: DataTypes.TEXT, allowNull: true }, // ImageKit URL of the profile photo
  // The rich self-service profile the employee completes: payroll, bank,
  // personal info, documents (numbers + ImageKit URLs), education, employment
  // history and performance. Kept as a JSON blob so sub-fields can evolve
  // without a migration for each one.
  profile: { type: DataTypes.JSON, defaultValue: {} },
  shiftId: { type: DataTypes.INTEGER, allowNull: true }, // assigned HrShift
  // Employee-record timeline: joined, profile updates, promotions, notes, etc.
  timeline: { type: DataTypes.JSON, defaultValue: [] },
  active: { type: DataTypes.BOOLEAN, defaultValue: true },
}, {
  tableName: 'hr_users',
  indexes: [{ name: 'idx_hr_users_email', unique: true, fields: ['email'] }],
});
HrUser.prototype.toJSON = function () {
  const o = Object.assign({}, this.get());
  o._id = o.id;
  delete o.passwordHash;
  return o;
};

// Branches the admin manages (feeds the Branch dropdown).
const HrBranch = sequelize.define('HrBranch', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(80), allowNull: false, unique: true },
  active: { type: DataTypes.BOOLEAN, defaultValue: true },
}, { tableName: 'hr_branches' });
HrBranch.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

// Departments the admin manages (feeds the Department dropdown).
const HrDepartment = sequelize.define('HrDepartment', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(80), allowNull: false, unique: true },
  active: { type: DataTypes.BOOLEAN, defaultValue: true },
}, { tableName: 'hr_departments' });
HrDepartment.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

// Work shifts the admin defines (with break window). Assigned per employee.
const HrShift = sequelize.define('HrShift', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(80), allowNull: false },
  startTime: { type: DataTypes.STRING(10), defaultValue: '' },  // "09:00"
  endTime: { type: DataTypes.STRING(10), defaultValue: '' },    // "18:00"
  breakStart: { type: DataTypes.STRING(10), defaultValue: '' },
  breakEnd: { type: DataTypes.STRING(10), defaultValue: '' },
  active: { type: DataTypes.BOOLEAN, defaultValue: true },
}, { tableName: 'hr_shifts' });
HrShift.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

// Holiday list — per branch (branch '' means all branches / company-wide).
const HrHoliday = sequelize.define('HrHoliday', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(120), allowNull: false },
  date: { type: DataTypes.DATEONLY, allowNull: false },
  branch: { type: DataTypes.STRING(80), defaultValue: '' },
}, { tableName: 'hr_holidays' });
HrHoliday.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

// Recruitment scaffolding — job posts. Structure only for now; functionality
// arrives in a later version.
const HrJobPost = sequelize.define('HrJobPost', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: { type: DataTypes.STRING(160), allowNull: false },
  branch: { type: DataTypes.STRING(80), defaultValue: '' },
  description: { type: DataTypes.TEXT, defaultValue: '' },
  status: { type: DataTypes.STRING(30), defaultValue: 'open' },
  createdById: { type: DataTypes.INTEGER, allowNull: true },
  createdByName: { type: DataTypes.STRING(120), defaultValue: '' },
}, { tableName: 'hr_job_posts' });
HrJobPost.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

// Recruitment scaffolding — candidates.
const HrCandidate = sequelize.define('HrCandidate', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(120), allowNull: false },
  email: { type: DataTypes.STRING(160), defaultValue: '' },
  phone: { type: DataTypes.STRING(40), defaultValue: '' },
  jobPostId: { type: DataTypes.INTEGER, allowNull: true },
  // Recruitment stage: applied → pipeline → onboarded (details later).
  stage: { type: DataTypes.STRING(30), defaultValue: 'applied' },
  recruiterId: { type: DataTypes.INTEGER, allowNull: true },
  notes: { type: DataTypes.TEXT, defaultValue: '' },
}, { tableName: 'hr_candidates' });
HrCandidate.prototype.toJSON = function () { const o = Object.assign({}, this.get()); o._id = o.id; return o; };

module.exports = {
  sequelize, Sequelize, Op,
  User, Report, Lead, Settings, AuditLog, Review, BusinessBrief, MonthlyTarget, LeadEmail,
  HrUser, HrBranch, HrDepartment, HrShift, HrHoliday, HrJobPost, HrCandidate,
  encrypt, decrypt, initDb, defaultPricing, pruneDuplicateIndexes,
};
